package skillgen

import (
	"strings"
	"testing"

	"github.com/Harness/forge/internal/pipeline"
	"github.com/Harness/forge/internal/protocol"
)

func TestQualitySkillContainsTaskRule(t *testing.T) {
	proto := &protocol.Protocol{
		Version: "1",
		Standards: []protocol.Standard{
			{ID: "compile", Name: "编译必须通过", Description: "每次修改后确认编译通过", Severity: "error", Enabled: true},
		},
		SessionRules: []protocol.SessionRule{
			{Instruction: "修改前先说意图", Mandatory: true, Trigger: "on_edit"},
		},
	}
	p := &pipeline.Pipeline{
		Project: "test-project",
		Mode:    "small",
	}

	content := buildQualitySkillContent(proto, p)

	if !strings.Contains(content, "Task Bridge Protocol") {
		t.Error("quality SKILL.md missing Task Bridge Protocol section")
	}
	if !strings.Contains(content, "编码前必做") {
		t.Error("quality SKILL.md missing mandatory pre-coding task start instruction")
	}
	if !strings.Contains(content, "强制顺序") {
		t.Error("quality SKILL.md missing forced gate sequence instruction")
	}
	if !strings.Contains(content, "--branch") {
		t.Error("quality SKILL.md missing --branch flag reference")
	}
	if !strings.Contains(content, "forge task start") {
		t.Error("quality SKILL.md missing 'forge task start' command reference")
	}
	if !strings.Contains(content, "forge task list") {
		t.Error("quality SKILL.md missing 'forge task list' command reference")
	}
	if !strings.Contains(content, "--ref <ref>") {
		t.Error("quality SKILL.md missing --ref in gate commands")
	}
}

// TestQualitySkillExperienceWorkflow guards the experience-review doc against
// regressing to the obsolete manual-JSON workflow. Proposals are now
// auto-generated by the code, so the skill must (a) NOT instruct agents to
// hand-author proposal JSON, and (b) document accept/show/generate instead.
func TestQualitySkillExperienceWorkflow(t *testing.T) {
	proto := &protocol.Protocol{
		Version: "1",
		Standards: []protocol.Standard{
			{ID: "compile", Name: "编译必须通过", Description: "", Severity: "error", Enabled: true},
		},
	}
	p := &pipeline.Pipeline{Project: "test-project", Mode: "small"}

	content := buildQualitySkillContent(proto, p)

	// New auto-generation reality must be documented.
	if !strings.Contains(content, "forge experience generate") {
		t.Error("quality SKILL.md missing 'forge experience generate' backfill command")
	}
	if !strings.Contains(content, "forge experience accept") {
		t.Error("quality SKILL.md missing 'forge experience accept' command")
	}
	if !strings.Contains(content, "自动生成") {
		t.Error("quality SKILL.md must state proposals are auto-generated")
	}

	// Obsolete manual-JSON instruction must be gone (it produced proposals with
	// the wrong ID format that `accept` rejected).
	if strings.Contains(content, "将 proposed rules 写入") {
		t.Error("quality SKILL.md still instructs manual proposal JSON writing (obsolete)")
	}
}
