package agentbridge

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpencodeTranslator generates .opencode/plugins/forge.ts — a real, blockable plugin.
// opencode (opencode.ai, Bun-based) loads TS plugins from .opencode/plugins/ at startup; the plugin's
// `tool.execute.before` hook runs before each tool call, and throwing inside it short-circuits the Effect so the tool
// never executes (verified at the opencode packages/opencode/src/session/tools.ts call site and
// packages/opencode/src/plugin/index.ts trigger). This puts opencode alongside
// claude-code/codex/cursor/windsurf as an agent where Forge gates can truly be enforced.
//
// opencode's hook callback builds a Claude-Code-shape stdin (session_id,
// hook_event_name, tool_name, tool_input), spawns `forge hook <name>`, and throws when forge
// blocks. No `--agent` normalizer is needed: the plugin emits the dialect forge parses natively.
//
// Field mapping (opencode tool args → Claude tool_input):
//   - write/edit/applypatch  args.filePath  → tool_input.file_path
//   - bash                    args.command   → tool_input.command
//   - write                   args.content   → tool_input.content
//   - edit                    args.newText   → tool_input.content  (opencode uses newText, not new_string)
//
// OpencodeTranslator 生成 .opencode/plugins/forge.ts——一个真实、可 block 的 plugin。
// opencode（opencode.ai，基于 Bun）启动时从 .opencode/plugins/ 加载 TS plugin；plugin 的
// `tool.execute.before` hook 在工具执行前跑，在其中 throw 会 short-circuit Effect，工具就
// 不会执行（已在 opencode 的 packages/opencode/src/session/tools.ts 调用点与
// packages/opencode/src/plugin/index.ts trigger 中验证）。这使 opencode 与
// claude-code/codex/cursor/windsurf 并列，成为 Forge gate 真正能 enforce 的 agent。
//
// opencode 的 hook callback 构造 Claude-Code-shape stdin（session_id、
// hook_event_name、tool_name、tool_input），spawn `forge hook <name>`，并在 forge
// block 时 throw。无需 `--agent` 归一化器：plugin 直接发 forge 原生解析的方言。
//
// 字段映射（opencode tool args → Claude tool_input）：
//   - write/edit/applypatch  args.filePath  → tool_input.file_path
//   - bash                    args.command   → tool_input.command
//   - write                   args.content   → tool_input.content
//   - edit                    args.newText   → tool_input.content  (opencode uses newText, not new_string)
type OpencodeTranslator struct{}

func (t *OpencodeTranslator) Translate(projectDir string, input *TranslationInput) error {
	if input.Protocol == nil {
		return fmt.Errorf("opencode: protocol is required")
	}

	pluginsDir := filepath.Join(projectDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginsDir, 0755); err != nil {
		return fmt.Errorf("opencode: create .opencode/plugins dir: %w", err)
	}

	content := buildOpencodePlugin()
	path := filepath.Join(pluginsDir, "forge.ts")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("opencode: write forge.ts: %w", err)
	}

	// Doc explains how to load the plugin (opencode auto-discovers .opencode/plugins/*.ts, so this README
	// is guidance for non-standard deployments / troubleshooting).
	//
	// 文档说明如何加载 plugin（opencode 自动发现 .opencode/plugins/*.ts，故此 README
	// 是给非标准部署/排错用的 guidance）。
	readmeDir := filepath.Join(projectDir, ".opencode")
	if err := os.MkdirAll(readmeDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "opencode: warning: cannot create dir for forge.README.md: %v\n", err)
	} else if err := os.WriteFile(filepath.Join(readmeDir, "forge.README.md"), []byte(buildOpencodeReadme()), 0644); err != nil {
		// The README is a promised Translate deliverable; a silent failure would
		// leave the user without the loading/troubleshooting doc. Warn, don't fail.
		fmt.Fprintf(os.Stderr, "opencode: warning: write forge.README.md: %v\n", err)
	}
	return nil
}

func (t *OpencodeTranslator) AgentType() AgentType {
	return AgentOpencode
}

// buildOpencodePlugin returns the TypeScript plugin source. The PRE_HOOKS /
// POST_HOOKS rosters embedded in the TS string mirror the per-matcher wiring in hooks/settings.go GenerateSettings —
// TestOpencodePluginWiring guards drift by extracting the `forge hook <name>` call sites from this string.
//
// buildOpencodePlugin 返回 TypeScript plugin 源码。嵌入 TS 字符串里的 PRE_HOOKS /
// POST_HOOKS 名单镜像 hooks/settings.go GenerateSettings 中的 per-matcher 接线——
// TestOpencodePluginWiring 通过从该字符串中提取 `forge hook <name>` 调用点来守卫 drift。
func buildOpencodePlugin() string {
	return `// AUTO-GENERATED by forge sync. Forge quality gates for opencode.
//
// opencode plugin contract (verified against opencode source):
//   - default-export a function (legacy module form; see opencode's
//     getLegacyPlugins in opencode/src/plugin/index.ts).
//   - return a Hooks object whose "tool.execute.before" runs before each tool
//     call; throwing inside it aborts the Effect, so the tool never executes
//     (opencode/src/session/tools.ts call site +
//     opencode/src/plugin/index.ts trigger).
//
// We spawn ` + "`forge hook <name>`" + ` with Claude-Code-shape stdin and throw
// when forge's JSON stdout reports {decision:"block"} (block is read from the
// JSON decision field, not an exit code — cobra surfaces forge's internal errors
// as exit 1, indistinguishable from a deny). forge is
// expected on PATH; if it's missing or errors we FAIL OPEN so we never lock the
// agent out of its own tooling.
import { spawn } from "node:child_process";

// opencode tool-name → Claude Code tool-name that forge keys enforcement on.
const CLAUDE_TOOL: Record<string, string> = {
  write: "Write",
  edit: "Edit",
  applypatch: "Write",
  bash: "Bash",
  read: "Read",
};

// Pre-tool gate roster, keyed by Claude tool name. Derived from
// hooks.ForgeHookSpec's PreToolUse matchers (Write|Edit and Bash) — keep in
// sync; TestOpencodePluginWiring asserts the derived parity. Edit carries the
// same gates as Write (the spec matcher is "Write|Edit"); read-before-edit is
// wired here so opencode gets the same shift-left blind-edit block Claude has.
const PRE_HOOKS: Record<string, string[]> = {
  Write: ["forge hook task-guard", "forge hook assertion-check", "forge hook read-before-edit"],
  Edit: ["forge hook task-guard", "forge hook assertion-check", "forge hook read-before-edit"],
  Bash: ["forge hook bash-guard", "forge hook hazard-guard"],
};
const POST_HOOKS: Record<string, string[]> = {
  Write: ["forge hook auto-compile", "forge hook workflow-test-guard"],
  Edit: ["forge hook auto-compile", "forge hook workflow-test-guard"],
  Bash: ["forge hook file-sentinel"],
  Read: ["forge hook tool-track"],
};

export default function forgePlugin() {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = PRE_HOOKS[claudeTool];
      if (!hooks) return; // no pre-tool gate for this tool
      const payload = buildPayload(input, claudeTool, "PreToolUse", output.args);
      for (const cmd of hooks) {
        const verdict = await runForge(cmd, payload);
        if (verdict.block) {
          throw new Error(` + "`forge blocked ${input.tool}: ${verdict.reason}`" + `);
        }
      }
    },
    "tool.execute.after": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = POST_HOOKS[claudeTool];
      if (!hooks) return;
      const payload = buildPayload(input, claudeTool, "PostToolUse", output.args);
      // Post hooks record/advise; a forge error must never abort the turn.
      // runForge itself fails open on spawn error / parse failure / 30s timeout
      // (never rejects), so a plain await is sufficient here.
      for (const cmd of hooks) {
        await runForge(cmd, payload);
      }
    },
  };
}

function buildPayload(input: any, claudeTool: string, event: string, args: any) {
  const tool_input: Record<string, string> = {};
  if (args?.filePath || args?.path) tool_input.file_path = args.filePath ?? args.path;
  if (args?.command) tool_input.command = args.command;
  if (args?.content) tool_input.content = args.content;
  if (args?.newText) tool_input.content = args.newText;
  return {
    session_id: input.sessionID ?? "",
    hook_event_name: event,
    tool_name: claudeTool,
    tool_input,
  };
}

` + tsSharedForgeSpawn
}

func buildOpencodeReadme() string {
	return `# Forge plugin for opencode

This plugin (` + "`.opencode/plugins/forge.ts`" + `) wires Forge quality gates into opencode.
opencode auto-discovers ` + "`.opencode/plugins/*.ts`" + ` at startup — no config needed.

## What it does
- ` + "`tool.execute.before`" + `: runs Forge's pre-tool gates (task-guard, assertion-check,
  bash-guard). If Forge blocks, the plugin throws and opencode aborts the tool call.
- ` + "`tool.execute.after`" + `: runs post-tool hooks (auto-compile, file-sentinel,
  workflow-test-guard) for recording/advisory. workflow-test-guard runs the
  internal/ci guard tests; its block path is advisory here (opencode swallows
  post-tool verdicts), so the test executes but cannot hard-block the edit.

## Requirements
- ` + "`forge`" + ` on PATH.
- Runs under Bun (opencode's runtime); ` + "`node:child_process`" + ` is available there.

## Troubleshooting
If tools stop working entirely, the plugin fails open on Forge errors — check
` + "`forge`" + ` is installed (` + "`forge --version`" + `) and on PATH.
`
}
