package agentbridge

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpencodeTranslator generates .opencode/plugins/forge.ts — a real,
// block-capable plugin. opencode (opencode.ai, Bun-based) loads TS plugins from
// .opencode/plugins/ at startup; a plugin's "tool.execute.before" hook runs
// before the tool executes and throwing inside it short-circuits the Effect,
// so the tool never runs (verified in opencode's packages/opencode/src/session/
// tools.ts call site and packages/opencode/src/plugin/index.ts trigger). This
// makes opencode — alongside claude-code/codex/cursor/windsurf — an agent where
// Forge gates actually enforce.
//
// opencode's hook callback builds Claude-Code-shape stdin (session_id,
// hook_event_name, tool_name, tool_input) and spawns `forge hook <name>`, then
// throws if forge blocks. No `--agent` normalizer is needed: the plugin emits
// the exact dialect forge parses natively.
//
// Field mapping (opencode tool args → Claude tool_input):
//   - write/edit/applypatch  args.filePath  → tool_input.file_path
//   - bash                    args.command   → tool_input.command
//   - write                   args.content   → tool_input.content
//   - edit                    args.newText   → tool_input.content  (opencode uses newText, not new_string)
type OpencodeTranslator struct{}

func (t *OpencodeTranslator) Detect(projectDir string) bool {
	return dirExists(filepath.Join(projectDir, ".opencode"))
}

func (t *OpencodeTranslator) Translate(projectDir string, input *TranslationInput) error {
	if input.Protocol == nil {
		return fmt.Errorf("opencode: protocol is required")
	}

	pluginsDir := filepath.Join(projectDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginsDir, 0755); err != nil {
		return fmt.Errorf("opencode: create .opencode/plugins dir: %w", err)
	}

	content := buildOpencodePlugin()
	path := filepath.Join(pluginsDir, "forge.ts")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("opencode: write forge.ts: %w", err)
	}

	// Document how to load the plugin (opencode auto-discovers .opencode/plugins/*.ts,
	// so this README is guidance for non-standard setups / troubleshooting).
	readmeDir := filepath.Join(projectDir, ".opencode")
	if err := os.MkdirAll(readmeDir, 0755); err == nil {
		_ = os.WriteFile(filepath.Join(readmeDir, "forge.README.md"), []byte(buildOpencodeReadme()), 0644)
	}
	// Generate opencode.json mcp entry — idempotent merge (see mcpconfig.go).
	if err := writeOpencodeMCP(projectDir); err != nil {
		return fmt.Errorf("opencode: failed to generate opencode.json mcp: %w", err)
	}
	return nil
}

func (t *OpencodeTranslator) AgentType() AgentType {
	return AgentOpencode
}

// buildOpencodePlugin returns the TypeScript plugin source. The PRE_HOOKS /
// POST_HOOKS rosters embedded in the TS string mirror the per-matcher wiring in
// hooks/settings.go GenerateSettings — TestOpencodePluginWiring guards drift by
// extracting the `forge hook <name>` call sites from this string.
func buildOpencodePlugin() string {
	return `// AUTO-GENERATED by forge sync. Forge quality gates for opencode.
//
// opencode plugin contract (verified against opencode source):
//   - default-export a function (legacy module form; see opencode's
//     getLegacyPlugins in opencode/src/plugin/index.ts).
//   - return a Hooks object whose "tool.execute.before" runs before each tool
//     call; throwing inside it aborts the Effect, so the tool never executes
//     (opencode/src/session/tools.ts call site +
//     opencode/src/plugin/index.ts trigger).
//
// We spawn ` + "`forge hook <name>`" + ` with Claude-Code-shape stdin and throw
// when forge's JSON stdout reports {decision:"block"} (block is read from the
// JSON decision field, not an exit code — cobra surfaces forge's internal errors
// as exit 1, indistinguishable from a deny). forge is
// expected on PATH; if it's missing or errors we FAIL OPEN so we never lock the
// agent out of its own tooling.
import { spawn } from "node:child_process";

// opencode tool-name → Claude Code tool-name that forge keys enforcement on.
const CLAUDE_TOOL: Record<string, string> = {
  write: "Write",
  edit: "Edit",
  applypatch: "Write",
  bash: "Bash",
  read: "Read",
};

// Pre-tool gate roster, keyed by Claude tool name. Same set Claude Code wires
// per matcher in hooks/settings.go — keep in sync.
const PRE_HOOKS: Record<string, string[]> = {
  Write: ["forge hook task-guard", "forge hook assertion-check"],
  Bash: ["forge hook bash-guard", "forge hook hazard-guard"],
};
const POST_HOOKS: Record<string, string[]> = {
  Write: ["forge hook auto-compile", "forge hook workflow-test-guard"],
  Bash: ["forge hook file-sentinel"],
  Read: ["forge hook tool-track"],
};

export default function forgePlugin() {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = PRE_HOOKS[claudeTool];
      if (!hooks) return; // no pre-tool gate for this tool
      const payload = buildPayload(input, claudeTool, "PreToolUse", output.args);
      for (const cmd of hooks) {
        const verdict = await runForge(cmd, payload);
        if (verdict.block) {
          throw new Error(` + "`forge blocked ${input.tool}: ${verdict.reason}`" + `);
        }
      }
    },
    "tool.execute.after": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = POST_HOOKS[claudeTool];
      if (!hooks) return;
      const payload = buildPayload(input, claudeTool, "PostToolUse", output.args);
      // Post hooks record/advise; a forge error must never abort the turn.
      for (const cmd of hooks) {
        await runForge(cmd, payload).catch(() => {});
      }
    },
  };
}

function buildPayload(input: any, claudeTool: string, event: string, args: any) {
  const tool_input: Record<string, string> = {};
  if (args?.filePath || args?.path) tool_input.file_path = args.filePath ?? args.path;
  if (args?.command) tool_input.command = args.command;
  if (args?.content) tool_input.content = args.content;
  if (args?.newText) tool_input.content = args.newText;
  return {
    session_id: input.sessionID ?? "",
    hook_event_name: event,
    tool_name: claudeTool,
    tool_input,
  };
}

` + tsSharedForgeSpawn
}

func buildOpencodeReadme() string {
	return `# Forge plugin for opencode

This plugin (` + "`.opencode/plugins/forge.ts`" + `) wires Forge quality gates into opencode.
opencode auto-discovers ` + "`.opencode/plugins/*.ts`" + ` at startup — no config needed.

## What it does
- ` + "`tool.execute.before`" + `: runs Forge's pre-tool gates (task-guard, assertion-check,
  bash-guard). If Forge blocks, the plugin throws and opencode aborts the tool call.
- ` + "`tool.execute.after`" + `: runs post-tool hooks (auto-compile, file-sentinel,
  workflow-test-guard) for recording/advisory. workflow-test-guard runs the
  internal/ci guard tests; its block path is advisory here (opencode swallows
  post-tool verdicts), so the test executes but cannot hard-block the edit.

## Requirements
- ` + "`forge`" + ` on PATH.
- Runs under Bun (opencode's runtime); ` + "`node:child_process`" + ` is available there.

## Troubleshooting
If tools stop working entirely, the plugin fails open on Forge errors — check
` + "`forge`" + ` is installed (` + "`forge --version`" + `) and on PATH.
`
}
