package agentbridge

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/MjxUpUp/Forge/internal/util"
)

// OpencodeTranslator installs forge.ts into opencode's user-level global plugin directory.
//
// OpencodeTranslator 把 forge.ts 装进 opencode 的 user-level 全局 plugin 目录
// （$XDG_CONFIG_HOME/opencode/plugins/forge.ts；XDG_CONFIG_HOME 未设时为
// ~/.config/opencode/plugins/forge.ts——opencode 官方文档的全局 plugin 位置，
// https://opencode.ai/docs/plugins/）。
// opencode（opencode.ai，基于 Bun）启动时从该目录加载 TS plugin；plugin 的
// `tool.execute.before` hook 在工具执行前跑，在其中 throw 会 short-circuit Effect，工具就
// 不会执行（已在 opencode 的 packages/opencode/src/session/tools.ts 调用点与
// packages/opencode/src/plugin/index.ts trigger 中验证）。这使 opencode 与
// claude-code/codex/cursor/windsurf 并列，成为 Forge gate 真正能 enforce 的 agent。
//
// 用户级路径对齐 kimi/claude-code 模型：一份全机器注册替代逐项目的
// .opencode/plugins/forge.ts 副本，forge init/sync 不再写项目目录（用户级资产迁移）。
// forge.ts 完全由 forge 拥有——Translate 直接覆盖写（无 merge）；
// StripOpenCodeUserPlugin 删除它。项目级 .opencode/forge.README.md 不再写
// （plugin 已全局化，加载说明归 forge 文档）。
//
// opencode 的 hook callback 构造 Claude-Code-shape stdin（session_id、
// hook_event_name、tool_name、tool_input、forge_agent），spawn `forge hook <name>`，并在 forge
// block 时 throw。无需 `--agent` 归一化器：plugin 直接发 forge 原生解析的方言。
// 归因走 payload 的 forge_agent 字段（HookInput.ForgeAgent）而非 --agent 后缀，
// 使命令名册对 TestOpencodePluginWiring 保持字节稳定。
//
// 字段映射（opencode tool args → Claude tool_input）：
//   - write/edit/applypatch  args.filePath  → tool_input.file_path
//   - bash                    args.command   → tool_input.command
//   - write                   args.content   → tool_input.content
//   - edit                    args.newText   → tool_input.content  (opencode uses newText, not new_string)
//
// 事件覆盖豁免（2026-08-16 接续审计登记）：本集成只接 opencode 的
// tool.execute.before/after plugin 入口（buildOpencodePlugin 的 PRE_HOOKS/POST_HOOKS），
// 未接任何会话生命周期入口，故以下 ForgeHookSpec 分组在 opencode 上永不触发：
// SessionStart 组（skill-scan/mcp-scan/init-suggest/task-resume）、Stop 组
// （task-verify/review-stop）、UserPromptSubmit 组（resume-reinject/skill-trigger）、
// PostCompact（compact-resume）。后果：无启动期安全扫描与 task-resume 注入，
// task-verify/review-stop 门禁与被动 skill 触发在此 host 缺席——opencode 上的
// 质量 enforce 限于上述 tool-hook 门禁。与 ForgeHookSpec（hooks/settings.go）内的
// host-coverage 注释互为镜像；skill-trigger 缺席另由 translator_test.go 的
// opencodeExemptions 钉住。
type OpencodeTranslator struct{}

func (t *OpencodeTranslator) Translate(projectDir string, input *TranslationInput) error {
	// 用户级 translator：刻意忽略 projectDir——注册是全机器生效（与 KimiTranslator
	// 同契约）。forge.ts 由 forge 拥有，故直接覆盖写（天然幂等），不做 merge。
	path, err := OpencodePluginPath()
	if err != nil {
		return fmt.Errorf("opencode: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("opencode: create global plugins dir: %w", err)
	}
	if err := util.AtomicWrite(path, []byte(buildOpencodePlugin()), 0644); err != nil {
		return fmt.Errorf("opencode: write forge.ts: %w", err)
	}
	return nil
}

func (t *OpencodeTranslator) AgentType() AgentType {
	return AgentOpencode
}

// OpencodePluginPath resolves the user-level global forge.ts plugin path.
//
// OpencodePluginPath 解析 user-level 全局 forge.ts plugin 路径：设了
// XDG_CONFIG_HOME 用 $XDG_CONFIG_HOME/opencode/plugins/forge.ts，否则
// ~/.config/opencode/plugins/forge.ts（opencode 按 XDG 约定解析全局配置目录，
// https://opencode.ai/docs/config/）。
func OpencodePluginPath() (string, error) {
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("cannot resolve user home: %w", err)
		}
		base = filepath.Join(home, ".config")
	}
	return filepath.Join(base, "opencode", "plugins", "forge.ts"), nil
}

// StripOpenCodeUserPlugin deletes the forge-owned user-level global plugin ($XDG_CONFIG_HOME/opencode/plugins/forge.ts or ~/.config/opencode/plugins/forge.ts).
//
// StripOpenCodeUserPlugin 删除 forge 拥有的 user-level 全局 plugin
// （$XDG_CONFIG_HOME/opencode/plugins/forge.ts 或
// ~/.config/opencode/plugins/forge.ts）。返回文件是否存在并被删除；文件不存在为
// 干净 no-op。plugins 目录里的其他文件一律不动（其余 plugin 归用户所有）。
func StripOpenCodeUserPlugin() (bool, error) {
	path, err := OpencodePluginPath()
	if err != nil {
		return false, err
	}
	if err := os.Remove(path); err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("opencode: remove forge.ts: %w", err)
	}
	return true, nil
}

// buildOpencodePlugin 返回 TypeScript plugin 源码。嵌入 TS 字符串里的 PRE_HOOKS /
// POST_HOOKS 名单镜像 hooks.ForgeHookSpec 中的 per-matcher 接线——
// TestOpencodePluginWiring 通过从该字符串中提取 `forge hook <name>` 调用点来守卫 drift。
func buildOpencodePlugin() string {
	return `// AUTO-GENERATED by forge sync. Forge quality gates for opencode.
//
// opencode plugin contract (verified against opencode source):
//   - default-export a function (legacy module form; see opencode's
//     getLegacyPlugins in opencode/src/plugin/index.ts).
//   - return a Hooks object whose "tool.execute.before" runs before each tool
//     call; throwing inside it aborts the Effect, so the tool never executes
//     (opencode/src/session/tools.ts call site +
//     opencode/src/plugin/index.ts trigger).
//
// We spawn ` + "`forge hook <name>`" + ` with Claude-Code-shape stdin and throw
// when forge's JSON stdout reports {decision:"block"} (block is read from the
// JSON decision field, not an exit code — cobra surfaces forge's internal errors
// as exit 1, indistinguishable from a deny). forge is
// expected on PATH; if it's missing or errors we FAIL OPEN so we never lock the
// agent out of its own tooling.
import { spawn } from "node:child_process";

// opencode tool-name → Claude Code tool-name that forge keys enforcement on.
const CLAUDE_TOOL: Record<string, string> = {
  write: "Write",
  edit: "Edit",
  applypatch: "Write",
  bash: "Bash",
  read: "Read",
};

// Pre-tool gate roster, keyed by Claude tool name. Derived from
// hooks.ForgeHookSpec's PreToolUse matchers (Write|Edit and Bash) — keep in
// sync; TestOpencodePluginWiring asserts the derived parity. Edit carries the
// same gates as Write (the spec matcher is "Write|Edit"); read-before-edit is
// wired here so opencode gets the same shift-left blind-edit block Claude has.
// conventions-write (2026-08-28): advisory write-time conventions pointers —
// wired (not exempted like skill-trigger) because it is the ONLY conventions
// delivery layer opencode can carry (its SessionStart group never fires here),
// and the plugin already parses allow-path stdout JSON on every call.
const PRE_HOOKS: Record<string, string[]> = {
  Write: ["forge hook freeze-guard", "forge hook task-guard", "forge hook assertion-check", "forge hook read-before-edit", "forge hook conventions-write"],
  Edit: ["forge hook freeze-guard", "forge hook task-guard", "forge hook assertion-check", "forge hook read-before-edit", "forge hook conventions-write"],
  Bash: ["forge hook bash-guard", "forge hook hazard-guard"],
};
const POST_HOOKS: Record<string, string[]> = {
  // test-nudge: mid-task test reminder (#4-E, advisory); tool-track on Bash: the
  // adherence audit's largest toollog hole (27.7k Bash calls, zero rows).
  Write: ["forge hook auto-compile", "forge hook workflow-test-guard", "forge hook test-nudge"],
  Edit: ["forge hook auto-compile", "forge hook workflow-test-guard", "forge hook test-nudge"],
  Bash: ["forge hook file-sentinel", "forge hook tool-track"],
  Read: ["forge hook tool-track"],
};

export default function forgePlugin() {
  return {
    "tool.execute.before": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = PRE_HOOKS[claudeTool];
      if (!hooks) return; // no pre-tool gate for this tool
      const payload = buildPayload(input, claudeTool, "PreToolUse", output.args);
      for (const cmd of hooks) {
        const verdict = await runForge(cmd, payload);
        if (verdict.block) {
          throw new Error(` + "`forge blocked ${input.tool}: ${verdict.reason}`" + `);
        }
      }
    },
    "tool.execute.after": async (input: any, output: any) => {
      const claudeTool = CLAUDE_TOOL[input.tool] ?? input.tool;
      const hooks = POST_HOOKS[claudeTool];
      if (!hooks) return;
      const payload = buildPayload(input, claudeTool, "PostToolUse", output.args);
      // Post hooks record/advise; a forge error must never abort the turn.
      // runForge itself fails open on spawn error / parse failure / 30s timeout
      // (never rejects), so a plain await is sufficient here.
      for (const cmd of hooks) {
        await runForge(cmd, payload);
      }
    },
  };
}

function buildPayload(input: any, claudeTool: string, event: string, args: any) {
  const tool_input: Record<string, string> = {};
  if (args?.filePath || args?.path) tool_input.file_path = args.filePath ?? args.path;
  if (args?.command) tool_input.command = args.command;
  if (args?.content) tool_input.content = args.content;
  if (args?.newText) tool_input.content = args.newText;
  return {
    session_id: input.sessionID ?? "",
    hook_event_name: event,
    tool_name: claudeTool,
    tool_input,
    // Attribution identity: forge reads forge_agent from the payload when no
    // --agent flag / FORGE_HOOK_AGENT env is present (HookInput.ForgeAgent).
    // A payload field (not an --agent suffix on the PRE_HOOKS/POST_HOOKS
    // command strings) keeps TestOpencodePluginWiring's command roster intact.
    //
    // 归因身份：无 --agent flag / FORGE_HOOK_AGENT env 时 forge 从 payload 读
    // forge_agent（HookInput.ForgeAgent）。用 payload 字段（而非给
    // PRE_HOOKS/POST_HOOKS 命令串加 --agent 后缀）保持
    // TestOpencodePluginWiring 的命令名册不变。
    forge_agent: "opencode",
  };
}

` + tsSharedForgeSpawn
}
