package agentbridge

import (
	"fmt"
	"os"
	"path/filepath"
)

// PiTranslator generates .pi/extensions/forge.ts — a real, block-capable
// extension for badlogic's pi agent framework (earendil-works/pi-coding-agent).
// pi auto-discovers .pi/extensions/*.ts at startup (loader.ts discoverAndLoad
// Extensions); an extension's default export is a factory receiving the
// ExtensionAPI. Subscribing to "tool_call" runs before the tool executes, and
// returning { block: true, reason } short-circuits the agent loop so the tool
// never runs — pi emits an error tool result carrying `reason` back to the LLM
// (agent-loop.ts beforeToolCall gate + runner.ts emitToolCall short-circuit,
// verified in pi source).
//
// This makes pi — alongside claude-code/codex/cursor/windsurf/opencode — an
// agent where Forge gates actually enforce.
//
// Field mapping (pi tool input → Claude tool_input): pi's file-path field is
// `path` (NOT file_path like Claude Code); bash command is `command`. The
// extension translates so the Claude-Code-shape stdin it builds parses natively
// in forge — no `--agent` normalizer needed.
type PiTranslator struct{}

func (t *PiTranslator) Detect(projectDir string) bool {
	return dirExists(filepath.Join(projectDir, ".pi"))
}

func (t *PiTranslator) Translate(projectDir string, input *TranslationInput) error {
	if input.Protocol == nil {
		return fmt.Errorf("pi: protocol is required")
	}

	extDir := filepath.Join(projectDir, ".pi", "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return fmt.Errorf("pi: create .pi/extensions dir: %w", err)
	}

	content := buildPiExtension()
	path := filepath.Join(extDir, "forge.ts")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("pi: write forge.ts: %w", err)
	}

	// Guidance doc for non-standard setups / troubleshooting. Auto-discovery
	// needs no config, so this is purely advisory.
	readmeDir := filepath.Join(projectDir, ".pi")
	if err := os.MkdirAll(readmeDir, 0755); err == nil {
		_ = os.WriteFile(filepath.Join(readmeDir, "forge.README.md"), []byte(buildPiReadme()), 0644)
	}
	return nil
}

func (t *PiTranslator) AgentType() AgentType {
	return AgentPi
}

// buildPiExtension returns the TypeScript extension source. The PRE_HOOKS /
// POST_HOOKS rosters embedded in the TS string mirror the per-matcher wiring in
// hooks/settings.go GenerateSettings — TestPiExtensionWiring guards drift by
// extracting the `forge hook <name>` call sites from this string.
func buildPiExtension() string {
	return `// AUTO-GENERATED by forge sync. Forge quality gates for pi (pi agent).
//
// pi extension contract (verified against pi source):
//   - default-export a factory (pi: ExtensionAPI) => void.
//   - subscribe pi.on("tool_call", handler); handler returns
//     { block: true, reason } to deny — the agent loop aborts the tool and
//     feeds ` + "`reason`" + ` back to the LLM as an error tool result
//     (coding-agent/src/core/extensions/types.ts ToolCallEventResult +
//     agent/src/agent-loop.ts beforeToolCall gate).
//
// We spawn ` + "`forge hook <name>`" + ` with Claude-Code-shape stdin and return
// { block: true } when forge's JSON stdout reports {decision:"block"} (block is
// read from the JSON decision field, not an exit code — cobra surfaces forge's
// internal errors as exit 1, indistinguishable from a deny). forge is expected
// on PATH; on missing/forge-error we FAIL OPEN.
// node:child_process is used (not pi.exec / Bun.spawn) so this runs under both
// Node and Bun — pi installs via npm (Node) but can also run as a Bun binary.
import { spawn } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// pi tool-name → Claude Code tool-name that forge keys enforcement on.
const CLAUDE_TOOL: Record<string, string> = {
  write: "Write",
  edit: "Edit",
  bash: "Bash",
  read: "Read",
};

// Pre-tool gate roster, keyed by Claude tool name. Same set Claude Code wires
// per matcher in hooks/settings.go — keep in sync.
const PRE_HOOKS: Record<string, string[]> = {
  Write: ["forge hook task-guard", "forge hook assertion-check"],
  Bash: ["forge hook bash-guard", "forge hook hazard-guard"],
};
const POST_HOOKS: Record<string, string[]> = {
  Write: ["forge hook auto-compile", "forge hook workflow-test-guard"],
  Bash: ["forge hook file-sentinel"],
  Read: ["forge hook tool-track"],
};

export default function forgeExtension(pi: ExtensionAPI) {
  pi.on("tool_call", async (event: any, ctx: any) => {
    const claudeTool = CLAUDE_TOOL[event.toolName] ?? event.toolName;
    const payload = buildPayload(event, claudeTool, "PreToolUse", ctx);
    const hooks = PRE_HOOKS[claudeTool];
    if (hooks) {
      for (const cmd of hooks) {
        const verdict = await runForge(cmd, payload);
        if (verdict.block) {
          return { block: true, reason: ` + "`forge blocked ${event.toolName}: ${verdict.reason}`" + ` };
        }
      }
    }
    // Post-tool gates: record/advise; never abort the turn on forge error.
    const post = POST_HOOKS[claudeTool];
    if (post) {
      const postPayload = buildPayload(event, claudeTool, "PostToolUse", ctx);
      for (const cmd of post) {
        await runForge(cmd, postPayload).catch(() => {});
      }
    }
    return undefined; // allow
  });
}

function buildPayload(event: any, claudeTool: string, hookEvent: string, ctx: any) {
  const tool_input: Record<string, string> = {};
  const input = event.input ?? {};
  // pi uses 'path' for file tools (not Claude's file_path); normalize here.
  if (input.path || input.file_path) tool_input.file_path = input.path ?? input.file_path;
  if (input.command) tool_input.command = input.command;
  if (input.content) tool_input.content = input.content;
  if (input.new_string) tool_input.content = input.new_string;
  return {
    session_id: event.toolCallId ?? "",
    hook_event_name: hookEvent,
    tool_name: claudeTool,
    tool_input,
  };
}

` + tsSharedForgeSpawn
}

func buildPiReadme() string {
	return `# Forge extension for pi

This extension (` + "`.pi/extensions/forge.ts`" + `) wires Forge quality gates into pi.
pi auto-discovers ` + "`.pi/extensions/*.ts`" + ` at startup — no config needed.

## What it does
- ` + "`pi.on(\"tool_call\", ...)`" + `: runs Forge's pre-tool gates (task-guard,
  assertion-check, bash-guard). If Forge blocks, the extension returns
  ` + "`{ block: true, reason }`" + ` and pi aborts the tool call, feeding ` + "`reason`" + ` to the
  LLM. Post-tool gates (auto-compile, file-sentinel, tool-track,
  workflow-test-guard) record/advisory. workflow-test-guard runs the internal/ci
  guard tests; its block is advisory on pi (post-tool verdicts are swallowed).
- Field mapping: pi's ` + "`path`" + ` → forge's ` + "`file_path`" + `.

## Requirements
- ` + "`forge`" + ` on PATH.
- Runs under Node (pi npm install) or Bun (pi binary); uses
  ` + "`node:child_process`" + ` for portability.

## Troubleshooting
If tools stop working entirely, the extension fails open on Forge errors — check
` + "`forge`" + ` is installed (` + "`forge --version`" + `) and on PATH.
`
}
