package scoring

// gitDiffStatChoreFixture 是 chore-fix-ci-cmd-forge dogfood 任务的
// `git diff --numstat` 原样快照（200 文件，v1.42 期）——scope 维度必须能处理的
// 真实大 diff 形状。存为数据，使 realCases() 在有意评分变更后能重建 fixture。
const gitDiffStatChoreFixture = `5	1	.gitignore
35	5	README.md
54	0	RELEASE.md
19	0	cmd/forge/main.go
1	1	go.mod
184	0	internal/act/conclusion.go
278	0	internal/act/conclusion_test.go
2	2	internal/agentbridge/claudecode.go
1	0	internal/agentbridge/codex.go
1	0	internal/agentbridge/cursor.go
5	3	internal/agentbridge/opencode.go
4	2	internal/agentbridge/pi.go
3	3	internal/agentbridge/translator_test.go
2	2	internal/agentbridge/types.go
1	0	internal/agentbridge/windsurf.go
122	0	internal/checklog/evidence.go
162	0	internal/checklog/evidence_test.go
6	1	internal/checklog/store.go
59	11	internal/checklog/types.go
141	0	internal/ci/release_workflow_test.go
56	0	internal/cli/aa_groups.go
94	0	internal/cli/aa_groups_test.go
164	0	internal/cli/act.go
119	0	internal/cli/act_test.go
76	8	internal/cli/cli_test.go
1	1	internal/cli/clone.go
73	0	internal/cli/dashboard.go
25	0	internal/cli/dashboard_test.go
1	1	internal/cli/docs_consistency_test.go
1	1	internal/cli/experience.go
2	2	internal/cli/experience_test.go
7	3	internal/cli/gate.go
43	0	internal/cli/gate_test.go
42	3	internal/cli/hazard.go
110	0	internal/cli/health.go
51	0	internal/cli/health_test.go
5	5	internal/cli/hook.go
1	1	internal/cli/hook_test.go
13	6	internal/cli/init.go
1	1	internal/cli/knowledge.go
15	9	internal/cli/mcp.go
1	1	internal/cli/phase_explosion_test.go
47	5	internal/cli/review.go
96	0	internal/cli/review_status_test.go
3	3	internal/cli/root.go
1	1	internal/cli/skills_adapters.go
2	2	internal/cli/skills_audit.go
4	47	internal/cli/skills_canonical.go
13	11	internal/cli/skills_canonical_test.go
1	1	internal/cli/skills_drift_check.go
66	0	internal/cli/skills_eval_baseline.go
232	0	internal/cli/skills_eval_loop_test.go
95	0	internal/cli/skills_eval_record.go
140	0	internal/cli/skills_eval_report.go
60	31	internal/cli/skills_evalgen.go
1	1	internal/cli/skills_install.go
1	1	internal/cli/skills_install_test.go
1	1	internal/cli/skills_list.go
1	1	internal/cli/skills_usage.go
2	2	internal/cli/skills_validate.go
3	3	internal/cli/snapshot.go
35	7	internal/cli/status.go
5	5	internal/cli/sync.go
2	2	internal/cli/sync_test.go
350	40	internal/cli/task.go
1	1	internal/cli/task_abort_test.go
202	0	internal/cli/task_acceptance_test.go
1	1	internal/cli/task_duplicate_test.go
110	0	internal/cli/task_scope_test.go
47	0	internal/cli/task_score_evidence_test.go
0	47	internal/cli/task_score_test.go
21	3	internal/cli/trace.go
1	1	internal/cli/validate.go
89	8	internal/cli/verify.go
187	0	internal/cli/verify_runtests_test.go
162	0	internal/dashboard/assets/index.html
11	0	internal/dashboard/embed.go
532	0	internal/dashboard/server.go
620	0	internal/dashboard/server_test.go
253	1	internal/e2e/hook_intercept_test.go
151	0	internal/e2e/hook_workflow_test_guard_test.go
1	1	internal/experience/generation.go
1	1	internal/experience/generation_test.go
1	1	internal/experience/integration.go
2	2	internal/experience/integration_test.go
2	2	internal/experience/review.go
1	1	internal/experience/review_test.go
1	1	internal/experience/types.go
116	0	internal/hazard/event.go
184	0	internal/hazard/event_test.go
6	3	internal/hazard/stamp.go
148	0	internal/health/summary.go
138	0	internal/health/summary_test.go
154	15	internal/hooks/embed.go
24	20	internal/hooks/settings.go
70	3	internal/hooks/settings_test.go
30	2	internal/mcpserver/server.go
284	5	internal/mcpserver/server_test.go
72	6	internal/mcpserver/tools.go
207	0	internal/mcpserver/tools_eval.go
1	1	internal/pipeline/executor.go
1	1	internal/pipeline/state.go
1	1	internal/pipeline/status.go
1	1	internal/pipeline/types.go
16	3	internal/projectroot/projectroot_test.go
1	1	internal/protocol/defaults.go
1	1	internal/protocol/types.go
112	0	internal/registry/registry.go
111	0	internal/registry/registry_test.go
66	27	internal/review/stamp.go
129	0	internal/review/stamp_test.go
55	0	internal/scoring/assertion.go
120	51	internal/scoring/evaluator.go
118	22	internal/scoring/evaluator_test.go
49	22	internal/scoring/git.go
9	1	internal/scoring/golden_test.go
162	0	internal/scoring/scope_test.go
4	0	internal/scoring/testdata/golden/golden_clean-baseline.json
6	2	internal/scoring/testdata/golden/golden_poor-quality.json
18	0	internal/scoring/types.go
20	6	internal/scoringtypes/types.go
1	1	internal/skillgen/generator.go
2	2	internal/skillgen/generator_test.go
3	3	internal/skillgen/qualitygen.go
2	2	internal/skillgen/qualitygen_test.go
65	0	internal/skillscanonical/resolve.go
54	0	internal/skillscanonical/resolve_test.go
1	1	internal/skillsdist/adapters.go
2	2	internal/skillsdist/install.go
2	2	internal/skillsdist/manifest.go
179	0	internal/skillseval/cases.go
117	0	internal/skillseval/cases_test.go
21	10	internal/skillseval/eval.go
521	0	internal/skillseval/runs.go
308	0	internal/skillseval/runs_test.go
1	1	internal/skillseval/usage.go
1	1	internal/skillsqa/registry.go
1	1	internal/snapshot/infer.go
1	1	internal/snapshot/snapshot_test.go
77	0	internal/taskpipeline/acceptance.go
80	0	internal/taskpipeline/acceptance_test.go
48	2	internal/taskpipeline/activity_ratio_test.go
455	0	internal/taskpipeline/cheatscan.go
277	0	internal/taskpipeline/cheatscan_test.go
1	1	internal/taskpipeline/concurrent_session_test.go
167	10	internal/taskpipeline/executor.go
87	0	internal/taskpipeline/executor_acceptance_test.go
112	0	internal/taskpipeline/executor_cheatscan_test.go
157	0	internal/taskpipeline/executor_scope_test.go
87	0	internal/taskpipeline/executor_skill_eval.go
111	0	internal/taskpipeline/executor_skill_eval_test.go
233	9	internal/taskpipeline/executor_test.go
178	0	internal/taskpipeline/scope.go
100	0	internal/taskpipeline/scope_test.go
1	1	internal/taskpipeline/session.go
1	1	internal/taskpipeline/session_test.go
2	2	internal/taskpipeline/state.go
1	1	internal/taskpipeline/testcapability.go
59	15	internal/taskpipeline/testcoverage.go
154	10	internal/taskpipeline/testcoverage_test.go
45	0	internal/taskpipeline/testrun.go
52	0	internal/taskpipeline/testrun_test.go
60	16	internal/taskpipeline/types.go
43	0	internal/taskpipeline/types_acceptance_test.go
41	0	internal/toolusage/read_edit_counts_test.go
23	1	internal/toolusage/store.go
1	1	npm/package.json
21	0	skills/code-review-gate/SKILL.md
4	0	skills/dev-workflow/SKILL.md
1	0	skills/integration-test-architecture/SKILL.md
13	1	skills/session-retrospective/SKILL.md
3	113	internal/cli/task.go
4	0	internal/cli/verify.go
21	3	internal/scoring/golden.go`
