package experience

import (
	"testing"
	"time"
)

func TestSaveLoadProposal_RoundTrip(t *testing.T) {
	root := t.TempDir()
	ts := time.Date(2026, 6, 7, 12, 0, 0, 0, time.UTC)

	original := &ExperienceProposal{
		ID:           "exp-test123",
		SourceReview: "feature/auth",
		Category:     "testing",
		Title:        "Always write integration tests",
		Description:  "Tasks without integration tests score poorly",
		Patterns:     []string{"no integration test", "only unit tests"},
		Severity:     "high",
		Status:       PropProposed,
		CreatedAt:    ts,
	}

	if err := SaveProposal(root, original); err != nil {
		t.Fatalf("SaveProposal: %v", err)
	}

	loaded, err := LoadProposal(root, "exp-test123")
	if err != nil {
		t.Fatalf("LoadProposal: %v", err)
	}

	if loaded.ID != original.ID {
		t.Errorf("ID = %q, want %q", loaded.ID, original.ID)
	}
	if loaded.SourceReview != original.SourceReview {
		t.Errorf("SourceReview = %q, want %q", loaded.SourceReview, original.SourceReview)
	}
	if loaded.Category != original.Category {
		t.Errorf("Category = %q, want %q", loaded.Category, original.Category)
	}
	if loaded.Title != original.Title {
		t.Errorf("Title = %q, want %q", loaded.Title, original.Title)
	}
	if loaded.Description != original.Description {
		t.Errorf("Description = %q, want %q", loaded.Description, original.Description)
	}
	if len(loaded.Patterns) != len(original.Patterns) {
		t.Fatalf("Patterns count = %d, want %d", len(loaded.Patterns), len(original.Patterns))
	}
	for i, p := range loaded.Patterns {
		if p != original.Patterns[i] {
			t.Errorf("Patterns[%d] = %q, want %q", i, p, original.Patterns[i])
		}
	}
	if loaded.Severity != original.Severity {
		t.Errorf("Severity = %q, want %q", loaded.Severity, original.Severity)
	}
	if loaded.Status != original.Status {
		t.Errorf("Status = %q, want %q", loaded.Status, original.Status)
	}
	if !loaded.CreatedAt.Equal(original.CreatedAt) {
		t.Errorf("CreatedAt = %v, want %v", loaded.CreatedAt, original.CreatedAt)
	}
}

func TestSaveProposal_AutoGeneratedFields(t *testing.T) {
	root := t.TempDir()

	p := &ExperienceProposal{
		SourceReview: "task/auto",
		Category:     "process",
		Title:        "Auto-generated ID test",
		Description:  "desc",
		Patterns:     nil,
		Severity:     "medium",
		Status:       PropProposed,
	}

	if err := SaveProposal(root, p); err != nil {
		t.Fatalf("SaveProposal: %v", err)
	}

	if p.ID == "" {
		t.Fatal("ID was not auto-generated")
	}
	if len(p.ID) < 5 {
		t.Errorf("ID too short: %q", p.ID)
	}
	if p.ID[:4] != "exp-" {
		t.Errorf("ID should start with 'exp-', got %q", p.ID)
	}
	if p.CreatedAt.IsZero() {
		t.Fatal("CreatedAt was not auto-generated")
	}
}

func TestListProposals_StatusFilter(t *testing.T) {
	root := t.TempDir()
	ts := time.Date(2026, 6, 7, 12, 0, 0, 0, time.UTC)

	proposals := []*ExperienceProposal{
		{
			ID: "exp-filter1", SourceReview: "task/a", Category: "testing",
			Title: "p1", Description: "d1", Patterns: nil,
			Severity: "high", Status: PropProposed, CreatedAt: ts,
		},
		{
			ID: "exp-filter2", SourceReview: "task/b", Category: "process",
			Title: "p2", Description: "d2", Patterns: nil,
			Severity: "medium", Status: PropAccepted, CreatedAt: ts,
		},
		{
			ID: "exp-filter3", SourceReview: "task/c", Category: "assertions",
			Title: "p3", Description: "d3", Patterns: nil,
			Severity: "low", Status: PropProposed, CreatedAt: ts,
		},
	}

	for _, p := range proposals {
		if err := SaveProposal(root, p); err != nil {
			t.Fatalf("SaveProposal %s: %v", p.ID, err)
		}
	}

	filtered, err := ListProposals(root, PropProposed)
	if err != nil {
		t.Fatalf("ListProposals with filter: %v", err)
	}
	if len(filtered) != 2 {
		t.Fatalf("ListProposals returned %d proposals, want 2", len(filtered))
	}

	for _, p := range filtered {
		if p.Status != PropProposed {
			t.Errorf("got status %q, want %q", p.Status, PropProposed)
		}
	}
}

func TestListProposals_NoFilter(t *testing.T) {
	root := t.TempDir()
	ts := time.Date(2026, 6, 7, 12, 0, 0, 0, time.UTC)

	proposals := []*ExperienceProposal{
		{
			ID: "exp-nofilter1", SourceReview: "task/a", Category: "testing",
			Title: "p1", Description: "d1", Patterns: nil,
			Severity: "high", Status: PropProposed, CreatedAt: ts,
		},
		{
			ID: "exp-nofilter2", SourceReview: "task/b", Category: "process",
			Title: "p2", Description: "d2", Patterns: nil,
			Severity: "medium", Status: PropAccepted, CreatedAt: ts,
		},
		{
			ID: "exp-nofilter3", SourceReview: "task/c", Category: "assertions",
			Title: "p3", Description: "d3", Patterns: nil,
			Severity: "low", Status: PropProposed, CreatedAt: ts,
		},
	}

	for _, p := range proposals {
		if err := SaveProposal(root, p); err != nil {
			t.Fatalf("SaveProposal %s: %v", p.ID, err)
		}
	}

	all, err := ListProposals(root, "")
	if err != nil {
		t.Fatalf("ListProposals no filter: %v", err)
	}
	if len(all) != 3 {
		t.Fatalf("ListProposals returned %d proposals, want 3", len(all))
	}
}

func TestUpdateProposalStatus(t *testing.T) {
	root := t.TempDir()
	ts := time.Date(2026, 6, 7, 12, 0, 0, 0, time.UTC)

	original := &ExperienceProposal{
		ID: "exp-status1", SourceReview: "task/x", Category: "testing",
		Title: "status test", Description: "desc", Patterns: nil,
		Severity: "high", Status: PropProposed, CreatedAt: ts,
	}

	if err := SaveProposal(root, original); err != nil {
		t.Fatalf("SaveProposal: %v", err)
	}

	if err := UpdateProposalStatus(root, "exp-status1", PropAccepted); err != nil {
		t.Fatalf("UpdateProposalStatus: %v", err)
	}

	loaded, err := LoadProposal(root, "exp-status1")
	if err != nil {
		t.Fatalf("LoadProposal: %v", err)
	}
	if loaded.Status != PropAccepted {
		t.Errorf("Status = %q, want %q", loaded.Status, PropAccepted)
	}
}

func TestLoadProposal_Nonexistent(t *testing.T) {
	root := t.TempDir()
	_, err := LoadProposal(root, "exp-nonexistent")
	if err == nil {
		t.Fatal("expected error for nonexistent proposal, got nil")
	}
	want := "not found"
	if !containsString(err.Error(), want) {
		t.Errorf("error = %q, want it to contain %q", err.Error(), want)
	}
}

func TestListProposals_EmptyDir(t *testing.T) {
	root := t.TempDir()
	proposals, err := ListProposals(root, "")
	if err != nil {
		t.Fatalf("ListProposals on empty dir: %v", err)
	}
	if len(proposals) != 0 {
		t.Errorf("expected 0 proposals, got %d", len(proposals))
	}
}
